myblog/blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_blog/', include('my_blog.urls', namespace='my_blog')),
    path('mdeditor/', include('mdeditor.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/my_blog/urls.py
# 引入path
from django.urls import path
# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'my_blog'

urlpatterns = [
path('article-list/', views.article_list, name='article_list'),
path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
path('categories/<int:pk>/', views.category, name='category'),
path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
path('tags/<int:pk>/', views.tag, name='tag'),
path('search/', views.search, name='search'),
path('time-line/', views.time_line, name='time_line'),
]

myblog/blog/my_blog/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User
from mdeditor.fields import MDTextField
import markdown
import re


# Create your models here.

# 文章关键词，用来作为SEO中keywords
class Keyword(models.Model):
    name = models.CharField('文章关键词', max_length=20)

    class Meta:
        verbose_name = '关键词'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name


# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240,
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('blog:tag', kwargs={'slug': self.slug})

    def get_article_list(self):
        '''返回当前标签下所有发表的文章列表'''
        return Article.objects.filter(tags=self)


# 文章分类
class Category(models.Model):
    name = models.CharField('文章分类', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240,
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('blog:category', kwargs={'slug': self.slug})

    def get_article_list(self):
        return Article.objects.filter(category=self)


# 文章
class Article(models.Model):
    IMG_LINK = '/static/blog/img/summary.png'
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField('文章摘要', max_length=230, default='文章摘要等同于网页description内容，请务必填写...')
    body = MDTextField(verbose_name='文章内容')
    image = models.ImageField('图片', upload_to='article/%Y%m', max_length=100)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    views = models.IntegerField('阅览量', default=0)
    slug = models.SlugField(unique=True)
    is_top = models.BooleanField('置顶', default=False)

    category = models.ForeignKey(Category, verbose_name='文章分类', on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    keywords = models.ManyToManyField(Keyword, verbose_name='文章关键词',
                                      help_text='文章关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.title[:20]

    def get_absolute_url(self):
        return reverse('my_blog:article_detail', kwargs={'id': self.id})

    def body_to_markdown(self):
        return markdown.markdown(self.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self):
        return Article.objects.filter(id__lt=self.id).order_by('-id').first()

    def get_next(self):
        return Article.objects.filter(id__gt=self.id).order_by('id').first()


# # 时间线
# class Timeline(models.Model):
#     COLOR_CHOICE = (
#         ('primary', '基本-蓝色'),
#         ('success', '成功-绿色'),
#         ('info', '信息-天蓝色'),
#         ('warning', '警告-橙色'),
#         ('danger', '危险-红色')
#     )
#     SIDE_CHOICE = (
#         ('L', '左边'),
#         ('R', '右边'),
#     )
#     STAR_NUM = (
#         (1, '1颗星'),
#         (2, '2颗星'),
#         (3, '3颗星'),
#         (4, '4颗星'),
#         (5, '5颗星'),
#     )
#     side = models.CharField('位置', max_length=1, choices=SIDE_CHOICE, default='L')
#     star_num = models.IntegerField('星星个数', choices=STAR_NUM, default=3)
#     icon = models.CharField('图标', max_length=50, default='fa fa-pencil')
#     icon_color = models.CharField('图标颜色', max_length=20, choices=COLOR_CHOICE, default='info')
#     title = models.CharField('标题', max_length=100)
#     update_date = models.DateTimeField('更新时间')
#     content = models.TextField('主要内容')
#
#     class Meta:
#         verbose_name = '时间线'
#         verbose_name_plural = verbose_name
#         ordering = ['update_date']
#
#     def __str__(self):
#         return self.title[:20]
#
#     def content_to_markdown(self):
#         return markdown.markdown(self.content,
#                                  extensions=['markdown.extensions.extra', ]
#                                  )


# 幻灯片
class Carousel(models.Model):
    number = models.IntegerField('编号', help_text='编号决定图片播放的顺序，图片不要多于5张')
    title = models.CharField('标题', max_length=20, blank=True, null=True, help_text='标题可以为空')
    content = models.CharField('描述', max_length=80)
    image = models.ImageField('轮播图', upload_to='banner/%Y%m', max_length=100)
    # img_url = models.CharField('图片地址', max_length=200)
    url = models.CharField('跳转链接', max_length=200, default='#', help_text='图片跳转的超链接，默认#表示不跳转')

    class Meta:
        verbose_name = '图片轮播'
        verbose_name_plural = verbose_name
        # 编号越小越靠前，添加的时间约晚约靠前
        ordering = ['number', '-id']

    def __str__(self):
        return self.content[:25]


# # 死链
# class Silian(models.Model):
#     badurl = models.CharField('死链地址', max_length=200, help_text='注意：地址是以http开头的完整链接格式')
#     remark = models.CharField('死链说明', max_length=50, blank=True, null=True)
#     add_date = models.DateTimeField('提交日期', auto_now_add=True)
#
#     class Meta:
#         verbose_name = '死链'
#         verbose_name_plural = verbose_name
#         ordering = ['-add_date']
#
#     def __str__(self):
#         return self.badurl


class FriendLink(models.Model):
    name = models.CharField('网站名称', max_length=50)
    description = models.CharField('网站描述', max_length=100, blank=True)
    link = models.URLField('友链地址', help_text='请填写http或https开头的完整形式地址')
    logo = models.URLField('网站LOGO', help_text='请填写http或https开头的完整形式地址', blank=True)
    create_date = models.DateTimeField('创建时间', auto_now_add=True)
    is_active = models.BooleanField('是否有效', default=True)
    is_show = models.BooleanField('是否首页展示', default=False)

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

    def __str__(self):
        return self.name

    def get_home_url(self):
        '''提取友链的主页'''
        u = re.findall(r'(http|https://.*?)/.*?', self.link)
        home_url = u[0] if u else self.link
        return home_url

    def active_to_false(self):
        self.is_active = False
        self.save(update_fields=['is_active'])

    def show_to_false(self):
        self.is_show = True
        self.save(update_fields=['is_show'])


class AboutBlog(models.Model):
    body = models.TextField(verbose_name='About 内容')
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)

    class Meta:
        verbose_name = 'About'
        verbose_name_plural = verbose_name

    def __str__(self):
        return 'About'

    def body_to_markdown(self):
        return markdown.markdown(self.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])


class AboutAuthor(models.Model):
    name = models.CharField(verbose_name='作者姓名', max_length=200)
    img_url = models.CharField('头像', max_length=200)
    job = models.CharField('岗位信息', max_length=200)
    description = models.CharField('个人简介', max_length=500)

    class Meta:
        verbose_name = '作者介绍'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

myblog/blog/my_blog/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from .models import Article, Carousel, AboutAuthor, Category, Tag

from django.core.paginator import Paginator


# Create your views here.
# 视图函数
def article_list(request):
    articles = Article.objects.all()
    allcategory = Category.objects.all()

    # paginator = Paginator(articles, 4)
    # # 获取 url 中的页码
    # page = request.GET.get('page')
    # # 将导航对象相应的页码内容返回给 articles
    #
    # articles = paginator.page(page)

    carousels = Carousel.objects.all()
    articles_top = Article.objects.all().filter(is_top=True)
    author = AboutAuthor.objects.get(name='Chenglulu')
    context = {'articles': articles, 'carousels': carousels, 'articles_top': articles_top, 'author': author,
               'allcategory': allcategory}
    return render(request, 'my_blog2/index.html', context)


def article_detail(request, id):
    # 取出相应的文章
    article = Article.objects.get(id=id)
    article.update_views()
    article.body = article.body_to_markdown()
    # 需要传递给模板的对象
    context = {'article': article}
    # 载入模板，并返回context对象
    return render(request, 'my_blog2/table.html', context)


def category(request, pk):
    # 记得在开始部分导入 Category 类
    cate = get_object_or_404(Category, pk=pk)
    title = cate.name
    post_list = Article.objects.filter(category=cate).order_by('-create_date')
    return render(request, 'my_blog2/list.html', context={'post_list': post_list, 'title': title})


def archive(request, year, month):
    post_list = Article.objects.filter(create_date__year=year,
                                       create_date__month=month,
                                       ).order_by('-create_date')
    title = str(year)+'年'+str(month)+'月文章'
    return render(request, 'my_blog2/list.html', context={'post_list': post_list, 'title': title})


def tag(request, pk):
    # 记得在开始部分导入 Tag 类
    t = get_object_or_404(Tag, pk=pk)
    title = t.name
    post_list = Article.objects.filter(tags=t).order_by('-create_date')
    return render(request, 'my_blog2/list.html', context={'post_list': post_list, 'title': title})


def search(request):
    keyboard = request.GET.get('keyboard')

    if keyboard:
        post_list = Article.objects.filter(
            Q(title__icontains=keyboard) |
            Q(body__icontains=keyboard)
        )
    else:
        post_list = Article.objects.all()

    title = '包含'+keyboard+'的文章'

    context = {'post_list': post_list, 'title': title}
    return render(request, 'my_blog2/list.html', context)


# 时间轴
def time_line(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'my_blog2/time-line.html', context)

myblog/blog/my_blog/templates/my_blog2/base.html
{% load static %}
<!doctype html>
<html lang="utf-8">
<head>
    <title>{% block title %}{% endblock title %}</title>
    <meta name="keywords" content="WordPress主题站,wordpress模板,wordpress博客主题,wordpress cms图片主题,maolai博客"/>
    <meta name="description"
          content="maolai博客分享各种wordpress主题下载,wordpress企业主题,wordpress cms主题,wordpress中文主题,wordpress视频主题,wordpress图片主题,wordpress博客模板,wordpress音乐主题"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'my_blog2/css/base.css' %}" rel="stylesheet">
    <link href="{% static 'my_blog2/css/index.css' %}" rel="stylesheet">
    <link href="{% static 'my_blog2/css/m.css' %}" rel="stylesheet">
    <script src="{% static 'my_blog2/js/jquery.min.js' %}"></script>
    <script src="{% static 'my_blog2/js/hc-sticky.js' %}"></script>
    <script src="{% static 'my_blog2/js/comm.js' %}"></script>
    <script src="{% static 'my_blog2/js/modernizr.js' %}"></script>
    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }
    </style>
    <!--[if lt IE 9]>

    <![endif]-->
</head>
<body>
{% include 'my_blog2/header.html' %}
{% block content %}{% endblock content %}
{% include 'my_blog2/footer.html' %}
<a href="#" class="cd-top">Top</a>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>

myblog/blog/my_blog/templates/my_blog2/footer.html
{% load static %}
<footer>
    <div class="footer">
        <div class="wxbox">
            <ul>
                <li><img src="{% static 'my_blog2/images/mmqrcode1597044665429.png' %}"><span>我的微信</span></li>
                <li><img src="{% static 'my_blog2/images/mmqrcode1597045074871.png' %}"><span>微信公众号</span></li>
            </ul>
        </div>
        <div class="bzjj">
            <h2>本站简介</h2>
            <p>GoogleSEO一些技巧,Python学习</p>
        </div>
        <div class="other">
            <h2>网站版权</h2>
            <p>本站所有主题/文章除标明原创外，均来自网络转载，版权归原作者所有，如果有侵犯到您的权益，请联系本站删除，谢谢！</p>
            <p>&nbsp;</p>
{#            <p>备案号：粤ICP备15025043号</p>#}
        </div>
    </div>
</footer>

myblog/blog/my_blog/templates/my_blog2/header.html
{% load static %}
{% load blog_extras %}
<header id="header">
    <div class="navbar">
        <div class="topbox">
            <p class="welcome">如果重新开始，我会做什么?</p>
            <div class="searchbox">
                <div id="search_bar" class="search_bar">
                    <form id="searchform" action="{% url 'my_blog:search' %}" method="get" name="searchform">
                        <input class="input" placeholder="想搜点什么呢.." type="text" name="keyboard" id="keyboard">
                        {#                        <input type="hidden" name="show" value="title"/>#}
                        {#                        <input type="hidden" name="tempid" value="1"/>#}
                        {#                        <input type="hidden" name="tbname" value="news">#}
                        {#                        <input type="hidden" name="Submit" value="搜索"/>#}
                        <p class="search_ico"><span></span></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="header-navigation">
        <nav>
            <div class="logo"><a href="{% url 'my_blog:article_list' %}">Chenglulu个人博客</a></div>
            <h2 id="mnavh"><span class="navicon"></span></h2>
            <ul id="starlist">
                <li><a href="{% url 'my_blog:article_list' %}">网站首页</a></li>
                <li><a href="#">关于我</a></li>
                <li><a href="{% url 'my_blog:time_line' %}">时间轴</a></li>
                <li><a href="#">教程</a></li>
                <li class="menu"><a href="#">分类</a>
                    <ul class="sub">
                    {% show_categories_banner %}

                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</header>

myblog/blog/my_blog/templates/my_blog2/index.html
{% extends "my_blog2/base.html" %}
{% load blog_extras %}
{% block title %}
    首页
{% endblock title %}

{% block content %}
    <div class="wrapper">
        <main>
            <div class="banner">
                <div id="banner" class="fader">
                    {% for carousel in carousels %}
                        <li class="slide"><a href="{% url 'my_blog:article_detail' carousel.id %}"
                                             title="{{ carousel.title }}"><img
                                src="{{ carousel.image.url }}"><span
                                class="imginfo">{{ carousel.title }}</span></a>
                        </li>
                    {% endfor %}
                    <div class="fader_controls">
                        <div class="page prev" data-target="prev">&lsaquo;</div>
                        <div class="page next" data-target="next">&rsaquo;</div>
                        <ul class="pager_list">
                        </ul>
                    </div>
                </div>
            </div>

            <div class="bloglist">
                <ul>
                    {% for article in articles %}
                        <li><i class="blogpic"><a href="#"><img src="{{ article.image.url }}" alt=""> </a></i>
                            <dl>
                                <dt><a href="{% url 'my_blog:article_detail' article.id %}"
                                       target="_blank">{{ article.title }}</a></dt>
                                <dd><span class="bloginfo">{{ article.summary }}...</span>
                                    <p class="timeinfo"><span class="lanmu"><a
                                            href="http://www.lmlblog.com/category/moban"
                                            target="_blank">{{ article.category }}</a></span><span
                                            class="date">{{ article.create_date }}</span></p>
                                    <a class="read" href="{% url 'my_blog:article_detail' article.id %}">阅读更多</a></dd>
                            </dl>
                        </li>
                    {% endfor %}
                </ul>
            </div>

{#            <div class="pagelist"><a title="Total record">&nbsp;<b>6</b> </a>&nbsp;&nbsp;&nbsp;<b>1</b>&nbsp;<a href="">2</a>&nbsp;<a#}
{#                    href="">3</a>&nbsp;<a href="">4</a>&nbsp;<a href="">5</a>&nbsp;<a href="">6</a>&nbsp;<a#}
{#                    href="">下一页</a>&nbsp;<a href="">尾页</a></div>#}
        </main>
        {% include 'my_blog2/sidebar.html' %}
    </div>
{% endblock content %}

myblog/blog/my_blog/templates/my_blog2/list.html
{% extends "my_blog2/base.html" %}
{% load blog_extras %}
{% block title %}
    {{ title }}
{% endblock title %}

{% block content %}
    <div class="wrapper">
        <main>
            <h2 class="place">您现在的位置是：网站首页&gt; <a href="/">{{ title }}</a></h2>
            <div class="bloglist">
                <ul>
                    {% for article in post_list %}
                        <li><i class="blogpic"><a href="#"><img src="{{ article.image.url }}" alt=""> </a></i>
                            <dl>
                                <dt><a href="{% url 'my_blog:article_detail' article.id %}"
                                       target="_blank">{{ article.title }}</a></dt>
                                <dd><span class="bloginfo">{{ article.summary }}...</span>
                                    <p class="timeinfo"><span class="lanmu"><a
                                            href="http://www.lmlblog.com/category/moban"
                                            target="_blank">{{ article.category }}</a></span><span
                                            class="date">{{ article.create_date }}</span></p>
                                    <a class="read" href="{% url 'my_blog:article_detail' article.id %}">阅读更多</a></dd>
                            </dl>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </main>
        {% include 'my_blog2/sidebar.html' %}
    </div>
{% endblock content %}

myblog/blog/my_blog/templates/my_blog2/table.html
{% extends "my_blog2/base.html" %}
{% load static %}
{% load blog_extras %}
{% block title %}
    {{ article.title }}
{% endblock title %}

{% block content %}
    <div class="wrapper">
        <main>
            <h2 class="place">您现在的位置是：<a href="{% url 'my_blog:article_list' %}">网站首页&gt;</a> <a href="/">{{ article.title }}</a></h2>
            <div class="infosbox">
                <div class="newsview">
                    <h3 class="news_title">{{ article.title }}</h3>
                    <div class="bloginfo">
                        <ul>
                            <li class="author">{{ article.author }}</li>
                            <li class="lmname">{{ article.category }}</li>
                            <li class="timer">{{ article.create_date }}</li>
                            <li class="view">
                                {{ article.views }}人已阅读
                            </li>
                        </ul>
                    </div>
                    <div class="tags">
                        {% for tag in article.tags.all %}
                             <a href="#" target="_blank">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                    <div class="news_about"><strong>简介</strong>{{ article.summary }}...
                    </div>
                    <div class="news_con">
                        {{ article.body|safe }}
                    </div>
                </div>
                <div class="share">
                    <p class="diggit"><a href="#">很赞哦！</a>(<b id="diggnum">19</b>)
                    </p>
                </div>
{#                <div class="nextinfo">#}
{#                    <p>上一篇：<a href="/blogs/876.html">个人和杂志Wordpress响应式清新博客主题Carrie#}
{#                    </a></p>#}
{#                    <p>下一篇：<a href="/blogs/">返回列表</a></p>#}
{#                </div>#}
{#                <div class="otherlink">#}
{#                    <h2>相关文章</h2>#}
{#                    <ul>#}
{#                        <li><a href="#" title="响应式Wordpress杂志主题Air Style">响应式Wordpress杂志主题Air Style</a></li>#}
{#                        <li><a href="#" title="个人/旅游/摄影/生活方式/作家/时尚博客主题Bloggo">个人/旅游/摄影/生活方式/作家/时尚博客主题Bloggo</a></li>#}
{#                        <li><a href="#" title="RealBlog-响应式WordPress博客主题">响应式WordPress博客主题RealBlog</a></li>#}
{#                        <li><a href="#" title="html5时尚个人博客模板-技术门户型">现代优雅干净的WordPress主题Wink</a></li>#}
{#                        <li><a href="#" title="现代优雅干净的WordPress主题Wink">html5个人博客模板主题《心蓝时间轴》</a></li>#}
{#                        <li><a href="#" title="古典个人博客模板《江南墨卷》">古典个人博客模板《江南墨卷》</a></li>#}
{#                        <li><a href="#" title="古典风格-个人博客模板">古典风格-个人博客模板</a></li>#}
{#                        <li><a href="#" title="Anonis-响应式Wordpress博客主题">Anonis-响应式Wordpress博客主题</a></li>#}
{#                        <li><a href="#" title="响应式博客Wordpress主题Bonex">响应式博客Wordpress主题Bonex</a></li>#}
{#                        <li><a href="#" title="Kass-多博客/杂志Wordpress主题">Wordpress多博客/杂志主题Kass</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="news_pl">#}
{#                    <h2>文章评论</h2>#}
{#                    <div class="gbko">#}
{#                        <div id="SOHUCS" sid="15"></div>#}
{#                        <script charset="utf-8" type="text/javascript"#}
{#                                src="https://changyan.sohu.com/upload/changyan.js' %}"></script>#}
{#                        <script type="text/javascript">#}
{#                            window.changyan.api.config({#}
{#                                appid: 'cytamwv5E',#}
{#                                conf: 'prod_9ded3f796a9a7ff9ba9fc72f58944d14'#}
{#                            });#}
{#                        </script>#}
{#                    </div>#}
{#                </div>#}
            </div>
        </main>
        {% include 'my_blog2/sidebar.html' %}
    </div>
{% endblock content %}

myblog/blog/my_blog/templates/my_blog2/time-line.html
{% extends "my_blog2/base.html" %}
{% load blog_extras %}
{% block title %}
    时间轴
{% endblock title %}

{% block content %}
    <div class="wrapper">
        <main>
            <h2 class="place">您现在的位置是：网站首页&gt; <a href="/">时光轴</a></h2>
            <div class="timebox">
                <ul>
                    {% for article in articles %}

                        <li><span>{{ article.create_date | date:"Y-m-d" }}</span><i><a
                                href="{% url 'my_blog:article_detail' article.id %}"
                                target="_blank">{{ article.title }}</a></i></li>
                    {% endfor %}
                </ul>
            </div>
{#            <div class="pagelist"><a title="Total record">&nbsp;<b>6</b> </a>&nbsp;&nbsp;&nbsp;<b>1</b>&nbsp;<a#}
{#                    href="">2</a>&nbsp;<a href="">3</a>&nbsp;<a href="">4</a>&nbsp;<a href="">5</a>&nbsp;<a#}
{#                    href="">6</a>&nbsp;<a#}
{#                    href="">下一页</a>&nbsp;<a href="">尾页</a></div>#}
        </main>
        {% include 'my_blog2/sidebar.html' %}
    </div>
{% endblock content %}